Repository Romitou/Wolfo, pull requests merged in 2020-07, with the labels that each got.

#54 🐛 Bugs fixs
  Wolfo/0-yaml.sk
  Wolfo/1-gui.sk
  Wolfo/2-sboard.sk
  Wolfo/5-main.sk
  Wolfo/7-game.sk
Labels: enhancement, translation

#53 Adding role and English file + optimizations
  .github/workflows/yaml-linter.yml
  .mergify.yml
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
  CONTRIBUTING_FR.md
  README.md
  README_EN.md
  README_FR.md
  Wolfo/0-yaml.sk
  Wolfo/1-gui.sk
  Wolfo/1-yaml.sk
  Wolfo/2-gui.sk
  Wolfo/2-sboard.sk
  Wolfo/3-sboard.sk
  Wolfo/4-chat.sk
  Wolfo/5-main.sk
  Wolfo/6-cosmetics.sk
  Wolfo/7-game.sk
  Wolfo/8-setup.sk
  Wolfo/9-miscelleanous.sk
  Wolfo/config.yml
  Wolfo/lang/en_us.yml
  Wolfo/lang/fr_fr.yml
  yaml-lint.yml
Labels: enhancement, language, needs testing

#56 🔫 Fix de la description du chasseur de prime
  Wolfo/lang/fr_fr.yml
Labels: language
